import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service · RateMyIdea",
  description:
    "The terms under which RateMyIdea operates, including how the Merit Board and the Highlight Board work.",
};

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      updated="27 August 2026"
      lede="These terms govern your use of ratemyidea.fun. By submitting an idea or buying a placement, you agree to them. Please read the sections on public content and on payments carefully, because both are final."
    >
      <section className="legal-section">
        <h2>
          <b>01</b>Who runs this site
        </h2>
        <p>
          RateMyIdea is operated by Ansh Jaisinghani, a sole proprietor based
          in Mumbai, Maharashtra, India. It is a small independent project,
          not a company.
        </p>
        <p>
          You can reach the operator at{" "}
          <a href="mailto:support@ratemyidea.fun">support@ratemyidea.fun</a>.
          Full contact details are on the <a href="/contact">contact page</a>.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>02</b>What the service does
        </h2>
        <p>
          You write a business idea in one short line. The site returns an
          automated score out of 100 and one short written assessment of
          that idea. Both are generated by an AI model against a published
          set of criteria.
        </p>
        <p>
          Your submission, its score and its assessment are then published
          on a public page and ranked on one or both of two boards:
        </p>
        <ul>
          <li>
            <b>The Merit Board.</b> Free. Every submission appears here,
            ordered by score alone. Placement on this board cannot be
            bought, influenced or altered by payment.
          </li>
          <li>
            <b>The Highlight Board.</b> Paid. A separate board where
            position is determined by how much has been paid for the
            placement.
          </li>
        </ul>
      </section>

      <section className="legal-section">
        <h2>
          <b>03</b>Everything you submit is public
        </h2>
        <p>
          This is the most important thing on this page. Any idea you submit
          is published immediately and visibly on the open internet,
          together with its score and assessment. It may be indexed by
          search engines, screenshotted, quoted and shared by anyone.
        </p>
        <div className="legal-note">
          <p>
            Do not submit anything confidential, commercially sensitive,
            subject to a non-disclosure agreement, or that you would not
            want a competitor to read.
          </p>
          <p>
            The site provides no confidentiality, no secrecy and no
            protection of any kind for the ideas submitted to it. If your
            idea needs protecting, do not put it here.
          </p>
        </div>
        <p>
          By submitting, you confirm the content is yours to share and you
          grant a worldwide, royalty free licence to publish, display, rank
          and reproduce it on the site and in promotional material about the
          site. You keep ownership of your idea. This licence covers display
          only.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>04</b>The score is an opinion, not advice
        </h2>
        <p>
          Scores and written assessments are generated automatically. They
          are subjective, frequently blunt, and often wrong. They are
          produced for entertainment and discussion.
        </p>
        <p>
          Nothing on this site is business advice, investment advice, legal
          advice, financial advice or a valuation. Do not fund, abandon,
          launch or shut down anything on the basis of a number produced
          here.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>05</b>The Highlight Board and what you are buying
        </h2>
        <p>
          A Highlight Board purchase buys one thing: a position in a public
          ranked list, held for as long as nobody pays more than you did. It
          is a promotional placement, not advertising inventory, not a
          subscription, and not a service delivered over time.
        </p>
        <ul>
          <li>
            Placements are priced in United States dollars, in whole
            dollars, with a minimum of five dollars and a maximum of
            999,999 dollars.
          </li>
          <li>
            Position on the board is determined by the amount paid. A
            higher amount ranks above a lower one.
          </li>
          <li>
            Your position is claimed when payment completes, not when it is
            initiated.
          </li>
          <li>
            Placements cannot be topped up or amended after purchase. Buying
            a second placement for the same idea creates a separate entry on
            the board at the new amount. The earlier placement remains at
            its own position and is not refunded, adjusted or replaced.
          </li>
          <li>
            You may include one website address and a product or company
            name with your placement. Link shorteners, affiliate parameters
            and redirect chains are not permitted.
          </li>
        </ul>
        <p>
          Your placement is delivered immediately on payment. There is no
          minimum duration and no guaranteed length of time at any position.
          Others can and will pay more than you did, and when they do, you
          move down. That is the entire mechanic of the board and it is
          visible to everyone before they pay.
        </p>
        <p>Amounts paid for every placement are displayed publicly alongside them.</p>
      </section>

      <section className="legal-section">
        <h2>
          <b>06</b>Payments
        </h2>
        <p>
          Payments are processed by Dodo Payments, acting as merchant of
          record. Your contract for the purchase is with Dodo Payments, who
          handle billing, applicable taxes and payment support. Card details
          are never received or stored by this site.
        </p>
        <p>
          All purchases are final. Please read the{" "}
          <a href="/refunds">refund policy</a> before paying.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>07</b>What you must not submit
        </h2>
        <p>Submissions and placements must not contain:</p>
        <ul>
          <li>Anything unlawful, or promoting unlawful activity</li>
          <li>
            Hate speech, harassment, threats, or content attacking a person
            or group
          </li>
          <li>Sexual or adult content</li>
          <li>Malware, phishing, or links intended to deceive</li>
          <li>
            Link shorteners, affiliate parameters, redirect chains or invite
            links
          </li>
          <li>Personal information about anyone, including yourself</li>
          <li>
            Impersonation of a person, brand or business you do not
            represent
          </li>
          <li>A business, product or service you have no connection to</li>
          <li>Content infringing anyone else&rsquo;s intellectual property</li>
          <li>Automated, bulk or duplicate submissions</li>
        </ul>
        <p>
          Placements or submissions breaching these rules are removed. Where
          the breach is deliberate, removal is without refund. Where content
          is removed in error, the refund policy applies.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>08</b>Removing your idea
        </h2>
        <p>
          You can ask for any submission to be removed at any time, for any
          reason, with no explanation required. Email{" "}
          <a href="mailto:support@ratemyidea.fun">support@ratemyidea.fun</a>{" "}
          with the link and it will be taken down, normally within two
          working days.
        </p>
        <p>
          Removing a free Merit Board submission costs nothing. Removing a
          paid Highlight Board placement at your own request does not
          trigger a refund, because the placement was delivered when you
          bought it.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>09</b>Eligibility
        </h2>
        <p>
          You must be at least 18 years old to submit an idea or buy a
          placement. Purchases must be made with a payment method you are
          authorised to use.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>10</b>Availability and liability
        </h2>
        <p>
          The site is provided as it is, with no warranty. It is a side
          project run by one person. It may be slow, may break, may go
          offline, and may one day be shut down entirely. Scores may be
          recalculated, boards may be reset, and features may change or
          disappear.
        </p>
        <p>
          To the fullest extent permitted by law, the operator&rsquo;s total
          liability to you for any claim connected to this site is limited
          to the amount you actually paid in the twelve months before the
          claim arose. For free users, that amount is zero.
        </p>
        <p>
          The operator is not liable for lost business, lost profits, lost
          opportunities, reputational harm, or any consequence of an idea
          being made public through your own submission of it.
        </p>
      </section>

      <section className="legal-section">
        <h2>
          <b>11</b>Changes and governing law
        </h2>
        <p>
          These terms may be updated. The date at the top of this page shows
          when they last changed. Continued use after a change means you
          accept the revised terms.
        </p>
      </section>
    </LegalLayout>
  );
}
